In [2]:
import numpy as np
import sympy
al=np.array([0.03,0.03,0.03,0.03])
be=np.array([0.07,0.07,0.07,0.07])
aln=np.array([0.03])
ben=np.array([0.07])

Ki=np.array([100,100,100,100,100])
Ci=np.array([25,25,25,25,25])
Ji=np.array([0.5,0.5,0.5,0.5,0.5])
H=np.array([5])

p1=243102
p2=231525
p3=220500
p4=210000
pn=200000

D=50000
rho=0.02

Q = sympy.symbols("Q")

T=np.array([[1/p1,1/p2,1/p3,1/p4]])*Q
Tn=np.array([[1/pn]])*Q
I=np.array([(be/(al+be))])*Q
In=np.array([(ben/(aln+ben)*pn-D)/pn])*Q

mnum=2
for m in range(0,mnum):#m=3일때의 문제가 됨
    #print(T)
    #print(T[m])
    tempt=np.array([T[m]])*(al/(al+be))
    #print(tempt)
    T=np.append(T, tempt, axis=0)
    #print(T)
    tempi=np.array([I[m]])*(al/(al+be))
    I=np.append(I,tempi, axis=0)
    
    temptn=np.array([Tn[m]])*(aln/(aln+ben))
    #print(temptn)
    Tn=np.append(Tn, temptn, axis=0)
    #print(Tn)
    tempin=np.array([In[m]])*(aln/(aln+ben))
    In=np.append(In,tempin, axis=0)
    

Imax_j=I.sum(axis=0)
Tsum_1=T.sum(axis=0)-T[mnum]
Isum_1=I.sum(axis=0)-I[mnum]

Ij=(Tsum_1*Isum_1+T[2]*Isum_1+T[2]*Imax_j)/2
Tj=(1+rho)*T.sum(axis=0)

Ij_mean=Ij/Tj


############ n-stage


Imax_n=In.sum(axis=0)
TD=Imax_n/D

Tsum_1_n=Tn.sum(axis=0)-Tn[mnum]
Isum_1_n=In.sum(axis=0)-In[mnum]

IT=(Tsum_1_n*Isum_1_n+Tn[2]*Isum_1_n+Tn[2]*Imax_n+TD*Imax_n)/2

Tnt=(1+rho)*(Tn.sum(axis=0)+TD)

Tt=Tj.sum(axis=0)+Tnt

I_mean = IT/Tt


##################cost

Ks=Ki.sum()


kptem=al/(al+be)
kpsum=0
for i in range(0,4): #4인 이유는 5번째 n으로 빼서
    kpi=0
    for m in range(0,mnum):
        kpi+=kptem[i]**m
    
    kpsum+=Ci[i]*kpi
Kp=[Q*kpsum]
print(Kp)


kisum=0
for i in range(0,4): #4인 이유는 5번째 n으로 빼서
    kii=0
    for m in range(0,mnum):
        kii+=kptem[i]**m
    
    kisum+=Ji[i]*kii
Ki=[Q*kisum]
print(Ki)

Kc=H*I_mean
print(Kc)

KP=(Ks+Kp+Ki)/Tt+Kc
print(KP[0])


        





print(T)
print(Tsum_1)
print(Tn)
print(Tsum_1_n)
print(I)
print(Isum_1)
print(In)
print(Isum_1_n)
print(Imax_n)
print(TD)
print(Tnt)
print(Imax_j)
print(Ij)
print(IT)
print(Tj)
print(Tt)
print(Ij_mean)
print(I_mean)
print(Ks)
print(Ks)




print(sympy.diff(KP[0]))

print(sympy.solve(sympy.diff(KP[0])))
EOQ=sympy.solve(sympy.diff(KP[0]))[1]
print(EOQ)
print(KP[0])
print(KP[0].subs(Q,EOQ))

[130.0*Q]
[2.6*Q]
[0.676439057144367*Q]
0.676439057144367*Q + 22228.9278840235*(132.6*Q + 500)/Q
[[4.11349968326052e-6*Q 4.31918799265738e-6*Q 4.53514739229025e-6*Q
  4.76190476190476e-6*Q]
 [1.23404990497816e-6*Q 1.29575639779721e-6*Q 1.36054421768707e-6*Q
  1.42857142857143e-6*Q]
 [3.70214971493447e-7*Q 3.88726919339164e-7*Q 4.08163265306122e-7*Q
  4.28571428571429e-7*Q]]
[5.34754958823868e-6*Q 5.61494439045459e-6*Q 5.89569160997732e-6*Q
 6.19047619047619e-6*Q]
[[5.0e-6*Q]
 [1.5e-6*Q]
 [4.5e-7*Q]]
[6.5e-6*Q]
[[0.7*Q 0.7*Q 0.7*Q 0.7*Q]
 [0.21*Q 0.21*Q 0.21*Q 0.21*Q]
 [0.063*Q 0.063*Q 0.063*Q 0.063*Q]]
[0.91*Q 0.91*Q 0.91*Q 0.91*Q]
[[0.45*Q]
 [0.135*Q]
 [0.0405*Q]]
[0.585*Q]
[0.6255*Q]
[1.251e-5*Q]
[1.98492e-5*Q]
[0.973*Q 0.973*Q 0.973*Q 0.973*Q]
[2.78169245830968e-6*Q**2 2.92078609221466e-6*Q**2 3.0668253968254e-6*Q**2
 3.22016666666667e-6*Q**2]
[6.086115e-6*Q**2]
[5.83211985092677e-6*Q 6.12374473598963e-6*Q 6.42993197278912e-6*Q
 6.75142857142857e-6*Q]
[4.49864251311341e-5*Q]
[0.4769

[[1.00000000e+02 5.00000000e+01 3.33333333e+01 2.50000000e+01]
 [5.00000000e+01 1.25000000e+01 3.33333333e+00 1.25000000e+00]
 [2.50000000e+01 3.12500000e+00 3.33333333e-01 6.25000000e-02]]
